name: reverse-nginx-proxy
services:
  yeasy-web-1:
    image: 571600835849.dkr.ecr.ap-southeast-1.amazonaws.com/yeasy/simple-web:latest
    hostname: yeasy-web-1
    container_name: yeasy-web-1
    networks:
      - nginx-proxy-nw

  yeasy-web-2:
    image: 571600835849.dkr.ecr.ap-southeast-1.amazonaws.com/yeasy/simple-web:latest
    hostname: yeasy-web-2
    container_name: yeasy-web-2
    networks:
      - nginx-proxy-nw

  nginx-reverse-proxy:
    image: nginx:latest
    hostname: nginx-reverse-proxy
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy-nw
    depends_on:
      - yeasy-web-1
      - yeasy-web-2
    
networks:
  nginx-proxy-nw:
    name: nginx-proxy-nw
    driver: bridge